CREATE TABLE tweet
(
    id BIGSERIAL NOT NULL,
    author_id BIGINT DEFAULT NULL,
    text VARCHAR(140) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY(id)
);
